fix

diff --git a/.github/workflows/Assignment3.4.yaml b/.github/workflows/Assignment3.4.yaml
--- a/.github/workflows/Assignment3.4.yaml
+++ b/.github/workflows/Assignment3.4.yaml
@@ -16,6 +16,7 @@ jobs:
       - name: Setup done
         run: |
           echo "Setup done"
+          exit 1  # Deliberately fail this job
          
 
   verify:
